---
abstract: '(De-)serialization from/to (compressed) JSON or Storable'
author:
  - 'Steffen Mueller <smueller@cpan.org>'
build_requires: {}
configure_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-FlexSerializer
no_index:
  directory:
    - t
    - inc
    - t
requires:
  Carp: 0
  Compress::Zlib: 0
  Constant::FromGlobal: 0
  File::Spec: 0
  IO::Uncompress::AnyInflate: 0
  JSON::XS: 0
  List::Util: 0
  Moose: 0
  MooseX::Types: 0
  Storable: 0
  Test::More: 0.88
  perl: 5.008001
resources:
  repository: https://github.com/tsee/Data-FlexSerializer
version: 1.03
