---
abstract: '(De-)serialization from/to (compressed) JSON or Storable'
author:
  - 'Steffen Mueller <smueller@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.113640'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-FlexSerializer
no_index:
  directory:
    - t
    - inc
requires:
  Any::Moose: 0
  Carp: 0
  Compress::Zlib: 0
  Constant::FromGlobal: 0
  IO::Uncompress::AnyInflate: 0
  JSON::XS: 0
  List::Util: 0
  Moose: 0
  Storable: 0
version: 1.00
