--- #YAML:1.0
name:               Data-FlexSerializer
version:            1.07
abstract:           (De-)serialization from/to (compressed) JSON or Storable
author:
    - Steffen Mueller <smueller@cpan.org>
license:            perl
distribution_type:  module
configure_requires:  {}
build_requires:  {}
requires:
    autodie:              0
    Carp:                 0
    Compress::Zlib:       0
    Constant::FromGlobal:  0
    File::Spec:           0
    IO::Uncompress::AnyInflate:  0
    JSON::XS:             0
    List::Util:           0
    Moose:                0
    MooseX::Types:        0
    perl:                 5.008001
    Sereal::Decoder:      0.15
    Sereal::Encoder:      0.17
    Storable:             0
    Test::More:           0.88
resources:
    repository:  https://github.com/tsee/Data-FlexSerializer
no_index:
    directory:
        - t
        - inc
        - t
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
