--- #YAML:1.0
name:               Data-FlexSerializer
version:            1.01
abstract:           (De-)serialization from/to (compressed) JSON or Storable
author:
    - Steffen Mueller <smueller@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Compress::Zlib:       0
    Constant::FromGlobal:  0
    IO::Uncompress::AnyInflate:  0
    JSON::XS:             0
    List::Util:           0
    Moose:                0
    MooseX::Types:        0
    Storable:             0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
